//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman_Server.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HangmanEntities : DbContext
    {
        public HangmanEntities()
            : base("name=HangmanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<gamematch> gamematch { get; set; }
        public virtual DbSet<gamematch_status> gamematch_status { get; set; }
        public virtual DbSet<language> language { get; set; }
        public virtual DbSet<player> player { get; set; }
        public virtual DbSet<word> word { get; set; }
    }
}
