//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman_Server.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class word
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public word()
        {
            this.gamematch = new HashSet<gamematch>();
        }
    
        public int id_word { get; set; }
        public string name { get; set; }
        public string hint { get; set; }
        public string description { get; set; }
        public string img_name { get; set; }
        public Nullable<int> id_category { get; set; }
        public Nullable<int> id_language { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gamematch> gamematch { get; set; }
        public virtual language language { get; set; }
    }
}
